using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.4.0.1")]
[assembly: AssemblyTitleAttribute("NAnt-Gui")]
[assembly: AssemblyDescriptionAttribute("Executes and edits NAnt build scripts")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2005, Colin Svingen")]
[assembly: AssemblyProductAttribute("NAnt-Gui")]

